[workspace]
resolver = "3"
members = ["driver", "core", "app", "main", "utility", "domain"]
default-members = ["main"]

[workspace.dependencies]
tracing = { version = "^0.1", features = ["log"] }
anyhow = "^1.0"
jiff = { version = "^0.2", features = ["serde"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = "symbols"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
clone_on_ref_ptr = "warn"
dbg_macro = "warn"
todo = "warn"
unimplemented = "warn"
branches_sharing_code = "allow"
collapsible_else_if = "allow"
collapsible_if = "allow"
unused_self = "allow"
box_collection = "allow"
cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
cast_precision_loss = "allow"
cast_sign_loss = "allow"
module_name_repetitions = "allow"
missing_errors_doc = "allow"

