[workspace]
resolver = "3"
members = ["driver", "core", "app", "main", "utility", "domain"]

[workspace.dependencies]
tracing = { version = "^0.1", features = ["log"] }
anyhow = "^1.0"
jiff = { version = "^0.2", features = ["serde"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = "symbols"

