[target.arm-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture armhf",
    # 既存のsources.listに [arch=amd64] を付与して混ざらないようにする
    "sed -i 's/deb http/deb [arch=amd64] http/g' /etc/apt/sources.list",
    # Debian 9 (Stretch) 以前のアーカイブからarmhfのリポジトリを強制的に追加する
    "SUITE=$(. /etc/os-release && echo $VERSION_CODENAME) && echo \"deb [arch=armhf] http://archive.debian.org/debian/ ${SUITE} main contrib non-free\" >> /etc/apt/sources.list",
    # アーカイブ版はセキュリティ証明書や有効期限が切れているため、チェックを無視して更新する
    "apt-get -o Acquire::Check-Valid-Until=false update || apt-get update",
    "DEBIAN_FRONTEND=noninteractive apt-get install -y --allow-unauthenticated libx11-dev:armhf libxcb1-dev:armhf libasound2-dev:armhf libxcb-render0-dev:armhf libxcb-shape0-dev:armhf libxcb-xfixes0-dev:armhf libfontconfig1-dev:armhf libfreetype6-dev:armhf"
]

[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update",
    "DEBIAN_FRONTEND=noninteractive apt-get install -y libx11-dev:armhf libxcb1-dev:armhf libasound2-dev:armhf libxcb-render0-dev:armhf libxcb-shape0-dev:armhf libxcb-xfixes0-dev:armhf libfontconfig1-dev:armhf libfreetype6-dev:armhf"
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get update",
    "DEBIAN_FRONTEND=noninteractive apt-get install -y libx11-dev libxcb1-dev libasound2-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libfontconfig1-dev libfreetype6-dev"
]
