use crate::TaskPriority;

pub(super) const PROJECTS: [&str; 20] = [
    "auth-service",
    "payment-gateway",
    "data-pipeline",
    "notification-engine",
    "analytics-dashboard",
    "user-profile-api",
    "search-indexer",
    "content-delivery",
    "billing-system",
    "recommendation-ml",
    "audit-logger",
    "file-storage-manager",
    "chat-websocket",
    "geo-location-service",
    "report-generator",
    "inventory-tracker",
    "admin-portal-backend",
    "security-scanner",
    "backup-recovery-tool",
    "metrics-collector",
];

pub(super) const TITLES: [&str; 20] = [
    "Implement JWT authentication",
    "Fix memory leak in background worker",
    "Refactor database connection pool",
    "Write unit tests for TaskNode",
    "Update README with Docker setup",
    "Configure CI/CD pipeline",
    "Optimize dashboard SQL queries",
    "Fix mobile responsive layout CSS",
    "Upgrade Cargo.toml dependencies",
    "Define OpenAPI schema",
    "Prepare sprint review demo",
    "Analyze Sentry error logs",
    "Implement Redis caching",
    "Add rate limiting middleware",
    "Sanitize HTML input fields",
    "Generate monthly PDF invoices",
    "Setup Prometheus metrics",
    "Encrypt sensitive user PII",
    "Automate daily DB backups",
    "Refactor legacy error handling",
];

pub(super) const TASK_DETAILS: [&str; 20] = [
    "Migrate user authentication from session-based to JWT tokens to enhance security. This includes implementing refresh token rotation.",
    "Investigate and fix a memory leak in the background log aggregation worker that occurs after 24 hours of continuous runtime.",
    "Introduce a connection pool using r2d2 for DuckDB to resolve connection exhaustion during peak hours and tune the timeout values.",
    "Write at least 5 unit test cases for the TaskNode struct to verify hierarchical relationships and ensure circular references are prevented.",
    "Update the README.md documentation with the latest local development setup instructions, including Docker configurations and Rust versions.",
    "Configure a CI/CD pipeline using GitHub Actions to automatically run cargo test, clippy, and typos on every pull request to main.",
    "Optimize low-performing SQL queries using EXPLAIN to reduce the loading time of the work-time dashboard, which currently takes over 3 seconds.",
    "Fix a CSS layout bug where the sidebar overlaps with the task list grid on screens smaller than 375px (e.g., iPhone SE).",
    "Upgrade major dependencies in Cargo.toml (specifically jiff and anyhow) to their latest stable versions and verify there are no breaking changes.",
    "Define the OpenAPI (Swagger) schema for the time-tracking API endpoints to ensure alignment between the frontend and backend teams.",
    "Prepare a demo video of the core features (task creation and time graphs) and draft a slide deck for this Friday's sprint review.",
    "Analyze Sentry error logs to pinpoint why users cannot save their work-time entries during peak traffic hours between 5:00 PM and 6:00 PM.",
    "Integrate Redis caching layer for the frequently accessed project configuration data to reduce direct load on the primary PostgreSQL database.",
    "Implement axum-rate-limiter middleware to restrict public endpoint requests to a maximum of 60 requests per minute per IP address.",
    "Review and sanitize all rich-text HTML inputs on the task description field using the ammonia crate to prevent Cross-Site Scripting (XSS) vulnerabilities.",
    "Implement a background job using typst to dynamically generate and format monthly PDF invoices for all premium tier enterprise clients.",
    "Expose custom application metrics via standard Prometheus format at the /metrics endpoint to monitor active user connections and queue latency.",
    "Implement AES-256-GCM encryption at the application level for sensitive user data, specifically storing encrypted phone numbers and raw addresses.",
    "Write a robust bash script triggered by cron to dump production database schemas, compress them via zstd, and upload directly to AWS S3.",
    "Refactor old legacy string-based errors into a clean, strongly-typed Enum system leveraging the thiserror crate for better maintainability.",
];

pub(super) const PRIORITIES: [TaskPriority; 3] =
    [TaskPriority::Low, TaskPriority::Medium, TaskPriority::High];
