[package]
name = "domain"
version = "8.3.1"
edition = "2024"

[dependencies]
tracing.workspace = true
anyhow.workspace = true
jiff.workspace = true
serde = { version = "^1.0", features = ["derive"] }
bitflags = "2.13.0"
rand = { version = "0.10.2", optional = true }

[features]
test-util = ["dep:rand"]

[lints]
workspace = true
